### PR TITLE
Add Chr, Strrev to ruby implementation

### PR DESCRIPTION
**Pull request by afman42**
- string:
  - [x] chr
  - [x] strrev
- unit test: 
  - [x] chr
  - [x] strrev

### CODE REVIEW

**Comment by afman42** [comment]
silakan di cek om @ronnygunawan @elianiva @aldy505

**Review by ronnygunawan — APPROVED** [review]
Nice! LGTM

**Comment by afman42** [comment]
cek lagi om @ronnygunawan

**Review by ronnygunawan — APPROVED** [review]
strrev LGTM

**Review by aldy505 — APPROVED** [review]

**Pull request merged**
